"""new migration

Revision ID: e8bc494fead8
Revises: 61fe6723ac1c
Create Date: 2023-05-25 15:00:03.904461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8bc494fead8'
down_revision = '61fe6723ac1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_forecast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predict', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand_forecast', schema=None) as batch_op:
        batch_op.drop_column('predict')

    # ### end Alembic commands ###
